version: "3.8"
services:
  peyk:
    image: farshidnooshi/peyk_service:latest
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DB=mydb
    ports:
      - "8080:8080"
    depends_on:
      - db
      - coinnews-container

  bepa:
    image: farshidnooshi/bepa_service:latest
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DB=mydb
      - MAILGUN_API_KEY=e88254122f9aadcfd8b789490578edaf-e5475b88-057fdc51
      - MAILGUN_DOMAIN=https://api.mailgun.net/v3/sandboxd810fa8fbc0944a39c6fb2760433b07d.mailgun.org
      - MAILGUN_SENDER=mailgun@sandboxd810fa8fbc0944a39c6fb2760433b07d.mailgun.org
    depends_on:
      - db
      - coinnews-container

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'mydb'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  coinnews-container:
    image: amirhossein21/coinnews.macos:v0.2
    volumes:
      - ./App/config.yml:/go/src/app/config.yml
    ports:
      - "8000:8000"

volumes:
  mysql-data:
