apiVersion: v1
kind: Secret
metadata:
  name: database-secret
type: Opaque
data:
  mysql-root-username: cm9vdA==  # base64-encoded value of 'root'
  mysql-root-password: cGFzc3dvcmQ=  # base64-encoded value of 'password'
