apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      initContainers:
        - name: init-script
          image: mysql:latest
          command:
            - "mysql"
            - "-h"
            - "localhost"
            - "-u"
            - "root"
            - "-ppassword"
            - "-e"
            - >
              CREATE DATABASE mydb; \
              CREATE USER 'root'@'%' IDENTIFIED BY 'password'; \
              GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
      containers:
        - name: db-container
          image: mysql:latest
          command: [ "--default-authentication-plugin=mysql_native_password" ]
          env:
            - name: MYSQL_DATABASE
              value: mydb
            - name: MYSQL_ROOT_PASSWORD
              value: password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pv
