apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi  # Adjust the storage size as per your requirements
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"  # Adjust the path as per your system's configuration

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Adjust the storage size as per your requirements
