apiVersion: v1
kind: PersistentVolume
metadata:
  name: myapp-database-pv
spec:
  capacity:
    storage: 1Gi  # Adjust the storage capacity as needed
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mysql  # Adjust the path as per your requirements

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myapp-database-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Adjust the storage capacity as needed
