apiVersion: v1
kind: PersistentVolume
metadata:
    name: mysql-database-pv
spec:
    capacity:
        storage: 1Gi # Adjust the storage capacity as needed
    accessModes:
        - ReadWriteOnce
    storageClassName: standard
    persistentVolumeReclaimPolicy: Retain
    hostPath:
        path: /data/mysql # Adjust the path as per your requirements

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mysql-database-pvc
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi # Adjust the storage capacity as needed
